language: python
python:
  - "3.6.4"

install:
  - pip install -r requirements.txt
  - pip install -e .
  
# command to run tests using py.test

script:
- pytest -v --ignore=scratch --ignore=build_dashboard.py